// Save verified remote paths, not image copies. Re-run when upstream adds forms.
import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const base = 'https://api.github.com/repos/PokeAPI/sprites/contents/';
async function get(url, json = true) {
  const r = await fetch(url, { signal: AbortSignal.timeout(30000) });
  if (!r.ok) throw Error(`${r.status}: ${url}`);
  return json ? r.json() : r.text();
}
const [pokemon, champions, home, items] = await Promise.all([
  get('https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/pokemon.csv', false),
  get(base + 'sprites/pokemon/versions/generation-ix/champions'),
  get(base + 'sprites/pokemon/other/home'),
  get(base + 'sprites/items/gen9'),
]);
const ids = Object.fromEntries(
  pokemon
    .trim()
    .split('\n')
    .slice(1)
    .map(line => line.split(','))
    .map(row => [row[1].replaceAll('-', ''), row[0]]),
);
const files = rows => new Set(rows.filter(r => r.type === 'file').map(r => r.name));
const championsFiles = files(champions),
  homeFiles = files(home);
const reference = JSON.parse(await readFile(new URL('public/data/reference.json', root)));
const megas = {};
const missing = [];
for (const [key, entry] of Object.entries(reference.species)) {
  if (!entry.forme.startsWith('Mega')) continue;
  const file = `${ids[key]}.png`;
  const folder = championsFiles.has(file)
    ? 'versions/generation-ix/champions'
    : homeFiles.has(file)
      ? 'other/home'
      : null;
  if (folder) megas[key] = `${folder}/${file}`;
  else missing.push(key);
}
const gen9Items = items
  .filter(r => r.type === 'file' && r.name.endsWith('.png'))
  .map(r => r.name)
  .sort();
await writeFile(
  new URL('src/artwork-data.js', root),
  `// Verified PokeAPI remote image paths (${new Date().toISOString().slice(0, 10)}). Generated by scripts/update-artwork.mjs.\nexport const MEGA_ARTWORK = ${JSON.stringify(megas, null, 2)};\nexport const GEN9_ITEMS = new Set(${JSON.stringify(gen9Items, null, 2)});\n`,
);
console.log(
  JSON.stringify({
    megaImages: Object.keys(megas).length,
    championsImages: Object.values(megas).filter(p => p.startsWith('versions')).length,
    gen9Items: gen9Items.length,
    missing,
  }),
);
